version: "3"

services:
  proxy:
    container_name: webproxy
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"

  web:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=crypto.localhost
      - VIRTUAL_PORT=80
    expose:
      - 80
    depends_on:
      - proxy